'Solution'
mate-academy/py-software-engineers pull request #111
Opened 2022-09-08 14:03 UTC by davidkrivko

2022-09-09 12:00 UTC, DmytroSvirsa requested changes

2022-09-09 12:00 UTC, DmytroSvirsa commented on app/main.py
> +print(android_dev.skills)
remove unused code

2022-09-09 12:00 UTC, DmytroSvirsa commented on app/main.py
> +    skills = []
make it as self attribute

2022-09-09 16:07 UTC, davidkrivko commented on app/main.py
> +    skills = []
put it in the constructor?

2022-09-12 07:07 UTC, Abnormaltype commented on app/main.py
> +    skills = []
yep

2022-09-12 07:07 UTC, Abnormaltype requested changes
put in the init

2022-09-13 14:14 UTC, closed without merging