'Solution_2'
mate-academy/py-software-engineers pull request #121
Opened 2022-09-13 14:15 UTC by davidkrivko

2022-09-13 14:50 UTC, Abnormaltype requested changes

2022-09-13 14:50 UTC, Abnormaltype commented on app/main.py
> +                                "JavaScript", "HTML", "CSS"])
remove this call, and implement logic without call init here

2022-09-13 14:50 UTC, Abnormaltype commented on app/main.py
> +print(android_dev.skills)
remove your tests

2022-09-19 08:02 UTC, IvanRamyk approved these changes
Well done!

2026-03-01 02:09 UTC, closed without merging