First_Solution
mate-academy/py-software-engineers pull request #1314
Opened 2024-12-06 19:52 UTC by neeeksa

2024-12-06 19:52 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-06 21:00 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-06 22:20 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-06 23:40 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-07 13:26 UTC, pavlopro requested changes
Tests Failed

2024-12-08 16:43 UTC, vsmutok requested changes

2024-12-08 16:43 UTC, vsmutok commented on app/main.py
> +        self.skills = ["JavaScript", "HTML", "CSS"]
```suggestion
        self.skills += ["JavaScript", "HTML", "CSS"]
```

2024-12-08 16:43 UTC, vsmutok commented on app/main.py
> +        self.skills = ["Python", "SQL", "Django"]
```suggestion
        self.skills += ["Python", "SQL", "Django"]
```

2024-12-08 16:43 UTC, vsmutok commented on app/main.py
> +        self.skills = ["Java", "Android studio"]
```suggestion
        self.skills += ["Java", "Android studio"]
```

2024-12-08 16:43 UTC, vsmutok commented on app/main.py
> +        self.skills = ["Python", "SQL", "Django", "JavaScript", "HTML", "CSS"]
`__init__` method redundant here

2024-12-09 19:37 UTC, pavlopro requested changes

2024-12-09 19:37 UTC, pavlopro commented on app/main.py
> +    def __init__(self, name: str) -> None:
`init` is redundant here

2024-12-11 07:30 UTC, vsmutok requested changes

2024-12-11 07:30 UTC, vsmutok commented on app/main.py
> +        super().create_awesome_web_page()
```suggestion
    def create_web_application(self) -> None:
        print(f"{self.name} started creating a web application...")
        self.create_powerful_api()
        self.create_awesome_web_page()
```

2024-12-11 19:46 UTC, pavlopro approved these changes
GJ

2025-01-21 18:42 UTC, closed without merging