Solution
mate-academy/py-software-engineers pull request #793
Opened 2024-01-02 12:31 UTC by TymurSh

2024-01-02 15:29 UTC, NikOneZ1 requested changes
It would be better to define skills in init method

2024-01-04 15:23 UTC, TymurSh commented
> It would be better to define skills in init method
Isn't it necessary to create skills as a class attribute in the task conditions? I can't pass the last test when skills is an instance attributes

2024-01-04 15:24 UTC, TymurSh commented on app/main.py
> -# write your code here
Isn't it necessary to create skills as a class attribute in the task conditions? I can't pass the last test when skills is an instance attributes

2024-01-05 11:40 UTC, TymurSh commented
Isn't it necessary to create skills as a class attribute in the task conditions? I can't pass the last test when skills is an instance attributes

2024-01-05 11:41 UTC, TymurSh reviewed
Isn't it necessary to create skills as a class attribute in the task conditions? I can't pass the last test when skills is an instance attributes

2024-03-29 20:25 UTC, closed without merging